modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="light-pistons"
version="1.0.0"
displayName="Light Pistons"
authors="AmyMialee"
description='''
Pistons that can push themselves backwards!
'''
[[dependencies.light-pistons]]
   modId="forge"
   mandatory=true
   versionRange="[36,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.light-pistons]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.5,1.17)"
   ordering="NONE"
   side="BOTH"
